Repository vmware-tanzu/octant, pull requests merged in 2021-01, with the labels that each got.

#1791 Remove Zenhub references and add review process
  CONTRIBUTING.md
  site/community.md
Labels: documentation

#1797 Fix streamer flake
  changelogs/unreleased/1797-GuessWhoSamFoo
  internal/log/streamer.go
  internal/log/streamer_test.go
Labels: testing

#1822 update electron for osx arm 64
  web/package-lock.json
  web/package.json
Labels: bug, dependencies

#1846 Add mutex to counter for runner test
  pkg/plugin/runner_test.go
Labels: testing

#1721 Custom clientconfig
  build.go
  cmd/octant-electron/main.go
  internal/api/websocket_state.go
  internal/api/websocket_state_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/commands/dash.go
  internal/config/dash.go
  internal/config/dash_test.go
  internal/config/fake/mock_dash.go
  internal/config/fake/mock_kubecontextdecorator.go
  internal/event/context.go
  internal/event/context_test.go
  internal/kubeconfig/fake/mock_loader.go
  internal/kubeconfig/kubeconfig.go
  internal/kubeconfig/kubeconfig_test.go
  internal/kubeconfig/testdata/kubeconfig-1.yaml
  internal/kubeconfig/testdata/kubeconfig-2.yaml
  internal/kubeconfig/testdata/kubeconfig.yaml
  pkg/dash/dash.go
  pkg/dash/dash_test.go
  pkg/dash/fake/mock_watcher_config.go
  pkg/dash/watcher.go
  pkg/dash/watcher_test.go
Labels: refactor

#1899 Fix various data races found when using -race build flag.
  internal/api/loading_state.go
  internal/api/websocket_client.go
  internal/kubeconfig/kubeconfig.go
  internal/objectstore/accessors.go
Labels: bug
